### PR TITLE
PL Translations

### PR DESCRIPTION
**Pull request by yaatzek**

### CODE REVIEW

**Comment by zephiK** [comment]
There are no translations in here, not sure why this is a pull request.

**Comment by yaatzek** [comment]
Damn it, not sure what happened here... Will check it.
23 cze 2015 10:45 PM "William" notifications@github.com napisał(a):

**Comment by yaatzek** [comment]
Check it now. Something got broken with my desktop github client...

**Comment by zephiK** [comment]
Squashed and merged, https://github.com/zephiK/android_packages_apps_Dialer/commit/d8b92ee7f468e380456fbe17e27c9db088dc1bcd

**Pull request closed without merging**
